export const CATEGORY_LIST_REQUEST = "CATEGORY_LIST_REQUEST";
export const CATEGORY_LIST_SUCCESS = "CATEGORY_LIST_SUCCESS";
export const CATEGORY_LIST_FAIL = "CATEGORY_LIST_FAIL";

export const CATEGORY_SINGLE_REQUEST = "CATEGORY_SINGLE_REQUEST";
export const CATEGORY_SINGLE_SUCCESS = "CATEGORY_SINGLE_SUCCESS";
export const CATEGORY_SINGLE_FAIL = "CATEGORY_SINGLE_FAIL";

export const CATEGORY_DELETE_REQUEST = "CATEGORY_DELETE_REQUEST";
export const CATEGORY_DELETE_SUCCESS = "CATEGORY_DELETE_SUCCESS";
export const CATEGORY_DELETE_FAIL = "CATEGORY_DELETE_FAIL";

export const CATEGORY_ADD_NEW_REQUEST = "CATEGORY_ADD_NEW_REQUEST";
export const CATEGORY_ADD_NEW_SUCCESS = "CATEGORY_ADD_NEW_SUCCESS";
export const CATEGORY_ADD_NEW_FAIL = "CATEGORY_ADD_NEW_FAIL";
